# Generated by Django 4.0.5 on 2022-07-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Cargo')),
                ('tipo', models.CharField(choices=[('A', 'ADMINISTRATIVO'), ('J', 'JURISDICCIONAL')], default='J', max_length=5, verbose_name='Tipo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalafon', models.CharField(blank=True, max_length=5, null=True, verbose_name='Escalafón')),
                ('remuneracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Remuneración')),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('cese', models.DateField(blank=True, null=True, verbose_name='Cese')),
                ('documento_designacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Documento de asignación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.dependencia')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.distritojudicial')),
                ('edificio', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.edificioinstitucional')),
                ('modulo', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.modulocoordinacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='persons.persona')),
                ('sede', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='departments.sedejudicial')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
