# Generated by Django 4.0.5 on 2022-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='inicio',
            field=models.DateField(default=None, verbose_name='Inicio'),
            preserve_default=False,
        ),
    ]
